language: python

matrix:
  include:
    - python: 3.7-dev
      env: TOXENV=py37
install:
  - pip install tox coveralls codecov
script:
  - tox
after_success:
  - codecov
  - coveralls
services:
  - postgresql
  - redis-server
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres