version: '2'

services:
  postgres:
    restart: always
    image: postgres:10-alpine
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: api
      POSTGRES_PASS: hackme
      POSTGRES_DB: storefront
  redis:
    restart: always
    image: redis
    expose:
      - 6379
    ports:
      - 6379:6379