"""Unique company name

Revision ID: f208299fca48
Revises: efc5266c95f5
Create Date: 2019-03-07 17:51:34.619595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f208299fca48'
down_revision = 'efc5266c95f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq__companies__name'), 'companies', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq__companies__name'), 'companies', type_='unique')
    # ### end Alembic commands ###
